### ISSUE TITLE
Support for new elasticsearch client for version 6

### ISSUE THREAD

**Issue by jbrenna** [M6Web/ElasticsearchBundle#21]
This bundle don't work with es6.

`Starting from Elasticsearch 6.0, all REST requests that include a body must also provide the correct content-type for that body.`

Would like to see support for elasticsearch client for version 6.

**Comment by Fabex** [comment]
Hi @jbrenna thank you for your issue.
We will try to do something to fix this issue.
But do you think you can create a PR to fix this issue?

**Comment by jbrenna** [comment]
Sorry, I didn't have version `5.3.2` of Elasticsearch PHP, do to some misconfiguration in my composer.json. It's working with ES6 now. Thanks for quick response.
